version: "2.4"

services:
  grpc-java-service:
    build:
      context: ./service

  proxy:
    build:
      context: ./grpc-proxy
    depends_on:
      - grpc-java-service


  web:
    build:
      context: ./web-app
    depends_on:
      - proxy
    ports:
      - 3000:3000

